defaults: &defaults
    docker:
        - image: circleci/openjdk:8-jdk
        - image: ryandjf/docker-spark
    working_directory: /home/circleci/project

version: 2
jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                keys:
                    - java-dependencies-{{ checksum "./CitibikeApiProducer/build.gradle" }}
            - restore_cache:
                keys:
                    - scala-dependencies-{{ checksum "./RawDataSaver/build.sbt" }}-{{ checksum "./StationConsumer/build.sbt"}}-{{ checksum "./StationTransformerNYC/build.sbt"}}
            - run:
                command: ./sbin/buildAll.sh               
            - persist_to_workspace:
                root: /home/circleci/project
                paths:
                    - CitibikeApiProducer/build/
                    - RawDataSaver/target/
                    - StationConsumer/target/
                    - StationTransformerNYC/target/
                    - Monitoring/target/
            - run:
                command: ls /home/circleci/project/
            - save_cache:
                key: scala-dependencies-{{ checksum "./RawDataSaver/build.sbt" }}-{{ checksum "./StationConsumer/build.sbt"}}-{{ checksum "./StationTransformerNYC/build.sbt"}}
                paths:
                    - "~/.ivy2/cache"
            - save_cache:
                key: java-dependencies-{{ checksum "./CitibikeApiProducer/build.gradle" }}
                paths:
                    - "~/.gradle"

    deploy:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                at: /home/circleci/project
            - add_ssh_keys:
                fingerprints:
                    - "42:91:7a:17:e1:5b:d8:33:8c:a9:78:58:09:20:b7:06"
            - run:
                command: ./sbin/deploy.sh

    deploy-qa:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                at: /home/circleci/project
            - add_ssh_keys:
                fingerprints:
                    - "67:90:b1:56:75:fa:15:ea:ac:e9:6f:58:d4:d5:51:e0"
            - run:
                command: ./sbin/deploy-qa.sh

    e2etest:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: /home/circleci/project
            - add_ssh_keys:
                  fingerprints:
                      - "67:90:b1:56:75:fa:15:ea:ac:e9:6f:58:d4:d5:51:e0"
            - run:
                  command: ls /home/circleci/project/
            - run:
                  command: ./sbin/runE2ETest.sh


workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build:
                filters:
                    branches:
                        only: 
                            - master
                            - start
            - approve-deploy-qa:
                type: approval
                requires: 
                    - build
            - deploy-qa:
                requires:
                    - approve-deploy-qa
            - e2etest:
                requires:
                    - deploy-qa

            - approve-deploy:
                type: approval
                requires: 
                    - build
            - deploy:
                requires:
                    - approve-deploy

